export const FETCH_COURSES = "FETCH_COURSES";
export const CREATE_COURSE = "CREATE_COURSE";
export const FETCH_COURSE_DETAIL = "FETCH_COURSE_DETAIL";
export const FETCH_SECTION_BY_COURSE = "FETCH_SECTION_BY_COURSE";
export const FETCH_LESSON_BY_COURSE_SECTION = "FETCH_LESSON_BY_COURSE_SECTION";
export const LOGGEDIN_USER = "LOGGEDIN_USER";
