export const FETCH_COURSES = "FETCH_COURSES";
export const CREATE_COURSE = "CREATE_COURSE";
export const FETCH_COURSE_DETAIL = "FETCH_COURSE_DETAIL";
export const FETCH_SECTION_BY_COURSE = "FETCH_SECTION_BY_COURSE";
export const CREATE_SECTION = "CREATE_SECTION";
export const SET_CURRENT_SECTION = "SET_CURRENT_SECTION";
export const FETCH_LESSON_BY_COURSE_SECTION = "FETCH_LESSON_BY_COURSE_SECTION";
export const CREATE_LESSON = "CREATE_LESSON";
export const SET_CURRENT_LESSON = "SET_CURRENT_LESSON";

export const ATTEND_COURSE_CURRENT_PAGE = "ATTEND_COURSE_CURRENT_PAGE";

export const UPDATE_LESSON_CONTENTS = "UPDATE_LESSON_CONTENTS";
export const LOGGEDIN_USER = "LOGGEDIN_USER";
